services:
  - type: web
    name: agrohelp-api
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"

    build:
      aptPackages:
        - ffmpeg
        - libjpeg-dev
        - zlib1g-dev
        - libfreetype6-dev

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4